### ISSUE TITLE
NOT A BUG | Weird `unexpected end of tag "for"` 

### ISSUE THREAD

**Issue by AlmogBaku** [paularmstrong/swig#588]
I have an XML file which I'm parsing using Swig:
```xml
{% for remote in remotes %}
<key>RemoteAddress</key>
<string>{{remote|split(':')|first}}</string>
{% endfor %}
```
When I'm running the script I'm receiving the following error:
```cli
➜  project git:(master) ✗ node server.js

/path/to/project/node_modules/swig/lib/utils.js:183
  throw new Error(message + '.');
        ^
Error: Unexpected end of tag "for" on line 91 in file /path/to/project/tpl/myfile.swig.xml.
    at Object.exports.throwError (/path/to/project/node_modules/swig/lib/utils.js:183:9)
    at parseTag (/path/to/project/node_modules/swig/lib/parser.js:532:15)
    at /path/to/project/node_modules/swig/lib/parser.js:640:15
    at Object.exports.each (/path/to/project/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/path/to/project/node_modules/swig/lib/parser.js:624:9)
    at parse (/path/to/project/node_modules/swig/lib/swig.js:354:19)
    at precompile (/path/to/project/node_modules/swig/lib/swig.js:486:23)
    at compile (/path/to/project/node_modules/swig/lib/swig.js:606:16)
    at Object.compileFile (/path/to/project/node_modules/swig/lib/swig.js:696:17)
    at Object.<anonymous> (/path/to/project/src/createCert.js:22:28)
```

If I'm adding a simple twig print(`{{ 'print' }}`) before the `for` directive it suddenly works:
```
<!-- {{'Weird fixes for unexpected end line of for'}} -->
{% for remote in remotes %}
<key>RemoteAddress</key>
<string>{{remote|split(':')|first}}</string>
{% endfor %}
```

**Comment by AlmogBaku** [comment]
Sorry it was a mistake with my swig template (I accidently closed print tag with only one `}`)
