### ISSUE TITLE
window is not defined in Hammer

### ISSUE THREAD

**Issue by julian-weinert** [paularmstrong/swig#623]
I added swing to my `package.json` using

```
"dependencies": {
		"swing": "~1.1.3"
}
```

npm installs successfully but I'm getting an exception from node:

```
/Library/WebServer/Node/REST/node_modules/swing/node_modules/hammerjs/hammer.js:2463
})(window, document, 'Hammer');
   ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Library/WebServer/Node/REST/node_modules/swing/node_modules/hammerjs/hammer.js:2463:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Library/WebServer/Node/REST/node_modules/swing/src/card.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Library/WebServer/Node/REST/node_modules/swing/src/stack.js:4:12)
    at Module._compile (module.js:460:26)
```

**Comment by EmirGluhbegovic** [comment]
Having same issue, looking up how to solve it. Any luck your side?

**Comment by Jonas-Drotleff** [comment]
Anyone with a workaround?

**Comment by Jonas-Drotleff** [comment]
I'm pretty sure you have this issue because you mixed up `swig` and `swing`.
`swig` is a templating framework while `swing` is 

> A swipeable cards interface

You opened this issue about the `swing` package in the `swig` repository so I guess you mixed them up. Replace `swing` with `swig` in your `package.json` and presumably also in your `server.js`, `index.js` or `main.js`
