### ISSUE TITLE
Works well with Express BUT not when Express + NGINX

### ISSUE THREAD

**Issue by estevo-de** [paularmstrong/swig#657]
Example of error message:
Error: Failed to lookup view "index" in views directory "/var/www/enewsletter.hamburg/views"
    at EventEmitter.render (/var/www/enewsletter.hamburg/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/var/www/enewsletter.hamburg/node_modules/express/lib/response.js:961:7)
    at module.exports (/var/www/enewsletter.hamburg/routes/index.js:6:7)
    at Layer.handle [as handle_request] (/var/www/enewsletter.hamburg/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/enewsletter.hamburg/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/www/enewsletter.hamburg/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/enewsletter.hamburg/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/enewsletter.hamburg/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/www/enewsletter.hamburg/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/enewsletter.hamburg/node_modules/express/lib/router/index.js:271:10)

No matter what you do to correct the path to the views folder, it gives the same message. If one is using only with Express then it works but not when using NGINX to redirect to Express

**Comment by estevo-de** [comment]
Hi all,
for those who wish to use with nginx, might want to just double check the directory.
I managed to solve it by looking at pug example and adjusting directory to match.

Thank you.
